"""create first table

Revision ID: 37b66c6467bd
Revises: 
Create Date: 2025-06-04 13:37:52.532688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b66c6467bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('weight_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reach_cm', sa.Float(), nullable=True),
    sa.Column('stance', sa.String(), nullable=True),
    sa.Column('association', sa.String(), nullable=True),
    sa.Column('weight_class_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('wins_ko', sa.Integer(), nullable=True),
    sa.Column('wins_submission', sa.Integer(), nullable=True),
    sa.Column('wins_decision', sa.Integer(), nullable=True),
    sa.Column('losses_ko', sa.Integer(), nullable=True),
    sa.Column('losses_submission', sa.Integer(), nullable=True),
    sa.Column('losses_decision', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_landed_per_min', sa.Float(), nullable=True),
    sa.Column('sig_striking_accuracy', sa.Float(), nullable=True),
    sa.Column('sig_strikes_absorbed_per_min', sa.Float(), nullable=True),
    sa.Column('sig_strike_defense', sa.Float(), nullable=True),
    sa.Column('takedowns_per_15_min', sa.Float(), nullable=True),
    sa.Column('takedown_accuracy', sa.Float(), nullable=True),
    sa.Column('takedown_defense', sa.Float(), nullable=True),
    sa.Column('submissions_per_15_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['weight_class_id'], ['weight_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fighters')
    op.drop_table('weight_classes')
    op.drop_table('users')
    # ### end Alembic commands ###
